#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

sed -i '/# build-prefer-ipv4$/d' /etc/gai.conf
if grep -q 'build-prefer-ipv4' /etc/gai.conf; then
    echo "build-prefer-ipv4 is still in /etc/gai.conf" >&2
    exit 1
fi
